Controllers/CarController.cs
using CadastroDeCarros.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Data.SqlClient;
using System.Drawing;
using System.Xml.Linq;

namespace CadastroDeCarros.Controllers
{
    public class CarController : Controller
    {
        public ActionResult Index()
        {
            List<ColorViewModel> colors = new List<ColorViewModel>();
            string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))

            {
                connection.Open();

                string sql = "SELECT * FROM Color";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            ColorViewModel color = new ColorViewModel()
                            {
                                Id = Convert.ToInt32(reader["Id"]),
                                Descricao = reader["Description"].ToString(),
                                Status = reader["Status"].ToString(),
                            };

                            colors.Add(color);
                        }
                    }
                }
            }

            return View(colors);
        }

        [HttpPost]
        public ActionResult Index(string search)
        {

            List<ColorViewModel> colors = new List<ColorViewModel>();

            string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                string sql;

                if (string.IsNullOrEmpty(search))
                {
                    sql = "SELECT * FROM Color";
                }
                else if (search.ToLower() == "ativo" || search.ToLower() == "inativo")
                {
                    sql = "SELECT * FROM Color WHERE Status = @Search";
                }
                else
                {
                    sql = "SELECT * FROM Color WHERE Description LIKE @Search";
                    search = "%" + search + "%";
                }

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    if (!string.IsNullOrEmpty(search))
                    {
                        command.Parameters.AddWithValue("@Search", search);
                    }
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            ColorViewModel color = new ColorViewModel()
                            {
                                Id = Convert.ToInt32(reader["Id"]),
                                Descricao = reader["Description"].ToString(),
                                Status = reader["Status"].ToString(),
                            };

                            colors.Add(color);
                        }
                    }
                }
            }

            return View(colors);
        }

        public ActionResult Create()
        {
            ViewBag.Colors = TakeColors().Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Descricao,
            })
            .ToList();
            ViewBag.Fuels = TakeFuels().Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Descricao,
            })
            .ToList();
            ViewBag.StatusList = new SelectList(new List<string>() { "Ativo", "Inativo" });
            return View();
        }

        [HttpPost]
        public ActionResult Create(CarViewModel model)
        {
            if (ModelState.IsValid)
            {
                InsertCar(model);
                return RedirectToAction("Index");
            }

            return View(model);
        }



        private List<ColorViewModel> TakeColors()
        {
            List<ColorViewModel> colors = new List<ColorViewModel>();
            string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))

            {
                connection.Open();

                string sql = "SELECT * FROM Color";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            ColorViewModel color = new ColorViewModel()
                            {
                                Id = Convert.ToInt32(reader["Id"]),
                                Descricao = reader["Description"].ToString(),
                                Status = reader["Status"].ToString(),
                            };

                            colors.Add(color);
                        }
                    }
                }
            }

            return colors;
        }

        private List<FuelViewModel> TakeFuels()
        {
            List<FuelViewModel> fuels = new List<FuelViewModel>();
            string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))

            {
                connection.Open();

                string sql = "SELECT * FROM Fuel";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            FuelViewModel fuel = new FuelViewModel()
                            {
                                Id = Convert.ToInt32(reader["Id"]),
                                Descricao = reader["Description"].ToString(),
                                Status = reader["Status"].ToString(),
                            };

                            fuels.Add(fuel);
                        }
                    }
                }
            }

            return fuels;
        }

        private static void InsertCar(CarViewModel model)
        {
            string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                string sql = "INSERT INTO Car (Plate, Renavam,ChassisNumber,EngineNumber,brand,Model,FuelId,ColorId,YearFactory,Status) VALUES (@Plate,@Renavam,@ChassisNumber,@EngineNumber,@brand,@Model, @FuelId,@ColorId,@YearFactory,@Status)";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@Plate", model.Plate);
                    command.Parameters.AddWithValue("@Renavam", model.Renavam);
                    command.Parameters.AddWithValue("@ChassisNumber", model.ChassisNumber);
                    command.Parameters.AddWithValue("@EngineNumber", model.EngineNumber);
                    command.Parameters.AddWithValue("@brand", model.Brand);
                    command.Parameters.AddWithValue("@Model", model.Model);
                    command.Parameters.AddWithValue("@ColorId", model.ColorId);
                    command.Parameters.AddWithValue("@FuelId", model.FuelId);
                    command.Parameters.AddWithValue("@YearFactory", model.YearFactory);
                    command.Parameters.AddWithValue("@Status", model.Status);

                    command.ExecuteNonQuery();
                }
            }
        }
    }
}

Controllers/ColorController.cs
using CadastroDeCarros.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Data.SqlClient;

namespace CadastroDeCarros.Controllers
{
    public class ColorController : Controller
    {
        public ActionResult Index()
        {
            List<ColorViewModel> colors = new List<ColorViewModel>();
            string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))

            {
                connection.Open();

                string sql = "SELECT * FROM Color";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            ColorViewModel color = new ColorViewModel()
                            {
                                Id = Convert.ToInt32(reader["Id"]),
                                Descricao = reader["Description"].ToString(),
                                Status = reader["Status"].ToString(),
                            };

                            colors.Add(color);
                        }
                    }
                }
            }

            return View(colors);
        }

        [HttpPost]
        public ActionResult Index(string search)
        {

            List<ColorViewModel> colors = new List<ColorViewModel>();

            string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                string sql;

                if (string.IsNullOrEmpty(search))
                {
                    sql = "SELECT * FROM Color";
                }
                else if (search.ToLower() == "ativo" || search.ToLower() == "inativo")
                {
                    sql = "SELECT * FROM Color WHERE Status = @Search";
                }
                else
                {
                    sql = "SELECT * FROM Color WHERE Description LIKE @Search";
                    search = "%" + search + "%";
                }

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    if (!string.IsNullOrEmpty(search))
                    {
                        command.Parameters.AddWithValue("@Search", search);
                    }
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            ColorViewModel color = new ColorViewModel()
                            {
                                Id = Convert.ToInt32(reader["Id"]),
                                Descricao = reader["Description"].ToString(),
                                Status = reader["Status"].ToString(),
                            };

                            colors.Add(color);
                        }
                    }
                }
            }

            return View(colors);
        }



        public ActionResult Create()
        {
            ViewBag.StatusList = new SelectList(new List<string>() { "Ativo", "Inativo" });
            return View();
        }

        [HttpPost]
        public ActionResult Create(ColorViewModel model)
        {
            if (model.CheckIfExists(model.Descricao))
            {
                ModelState.AddModelError("Descricao", "A descrição já foi usada");
                ViewBag.StatusList = new SelectList(new List<string>() { "Ativo", "Inativo" });
                return View(model);
            }

            if (ModelState.IsValid)
            {
                string connectionString ;
                SqlConnection conn;
                connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
                conn = new SqlConnection(connectionString);
                {
                    string sql = "INSERT INTO Color (Description, Status) VALUES (@Description, @Status)";
                    using (SqlCommand cmd = new SqlCommand(sql, conn))
                    {
                        cmd.Parameters.AddWithValue("@Description", model.Descricao);
                        cmd.Parameters.AddWithValue("@Status", model.Status);

                        conn.Open();
                        cmd.ExecuteNonQuery();
                    }
                }

                return RedirectToAction("Index");
            }

            return View(model);
        }
        public ActionResult Edit(int id)
        {
            ColorViewModel item = null;
            ViewBag.StatusList = new SelectList(new List<string>() { "Ativo", "Inativo" });
            string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();
        
                string sql = "SELECT * FROM Color WHERE Id = @Id";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@Id", id);

                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            item = new ColorViewModel()
                            {
                                Id = Convert.ToInt32(reader["Id"]),
                                Descricao = reader["Description"].ToString(),
                                Status = reader["Status"].ToString(),
                            };
                        }
                    }
                }
            }
            return View(item);
        }

        [HttpPost]
        public ActionResult Edit(ColorViewModel model)
        {
            if (ModelState.IsValid)
            {
                string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
                using (SqlConnection connection = new SqlConnection(connectionString))
                {
                    connection.Open();

                    string sql = "UPDATE Color SET Description = @Description, Status = @Status WHERE Id = @Id";
                    using (SqlCommand command = new SqlCommand(sql, connection))
                    {
                        command.Parameters.AddWithValue("@Description", model.Descricao);
                        command.Parameters.AddWithValue("@Status", model.Status);
                        command.Parameters.AddWithValue("@Id", model.Id);

                        command.ExecuteNonQuery();
                    }
                }

                return RedirectToAction("Index");
            }

            return View(model);
        }

        public ActionResult Delete(int id)
        {
            ColorViewModel item = null;
            string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                string sql = "SELECT * FROM Color WHERE Id = @Id";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@Id", id);

                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        if (reader.Read())
                        {
                            item = new ColorViewModel()
                            {
                                Id = Convert.ToInt32(reader["Id"]),
                                Descricao = reader["Description"].ToString(),
                                Status = reader["Status"].ToString(),
                            };
                        }
                    }
                }
            }
            return View(item);
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(int id)
        {
            string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                string sql = "DELETE FROM Color WHERE Id = @Id";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    command.Parameters.AddWithValue("@Id", id);
                    command.ExecuteNonQuery();
                }
            }

            return RedirectToAction("Index");
        }
    }

}

Views/Car/Create.cshtml
@model CadastroDeCarros.Models.CarViewModel

@{
    ViewData["Title"] = "Cadastro de Carro";
}

<h1>Cadastro de Carro</h1>

<hr />
@using (Html.BeginForm("Create", "Car", FormMethod.Post))
{
    <div class="form-group">
        <label for="Plate" class="control-label">Placa</label>
        <input type="text" id="Plate" name="Plate" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Renavam" class="control-label">Renavam</label>
        <input id="Renavam" name="Renavam" class="form-control" />
    </div>
    <div class="form-group">
        <label for="ChassisNumber" class="control-label">Número do Chassi</label>
        <input id="ChassisNumber" name="ChassisNumber" class="form-control" />
    </div>
    <div class="form-group">
        <label for="EngineNumber" class="control-label">Número do Motor</label>
        <input id="EngineNumber" name="EngineNumber" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Brand" class="control-label">Marca</label>
        <input id="Brand" name="Brand" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Model" class="control-label">Modelo</label>
        <input id="Model" name="Model" class="form-control" />
    </div>
    <div class="form-group">
        <label for="FuelId" class="control-label">Combustivel</label>
        <select id="FuelId" name="FuelId" class="form-control" asp-items="ViewBag.Fuels"></select>
    </div>
    <div class="form-group">
        <label for="ColorId" class="control-label">Cor</label>
        <select id="ColorId" name="ColorId" class="form-control" asp-items="ViewBag.Colors"></select>
    </div>
    <div class="form-group">
        <label for="YearFactory" class="control-label">Ano de Fabricação</label>
        <input id="YearFactory" name="YearFactory" class="form-control" />
    </div>
    <div class="form-group">
        <label for="Status" class="control-label">Name</label>
        <select id="Status" name="Status" class="form-control" asp-items="ViewBag.StatusList"></select>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
}

<br />
<div>
    <a class="btn btn-danger" asp-action="Index">Voltar para lista</a>
</div>

Views/Car/Delete.cshtml
@model CadastroDeCarros.Models.ColorViewModel

@{
    ViewData["Title"] = "Deletar Cor";
}
<h1>Deletar Cor</h1>

<h2>Tem certeza de que deseja excluir este item?</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Descricao)</dt>
        <dd>@Html.DisplayFor(model => model.Descricao)</dd>

        <dt>@Html.DisplayNameFor(model => model.Status)</dt>
        <dd>@Html.DisplayFor(model => model.Status)</dd>
    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "Color"))
    {
        @Html.HiddenFor(model => model.Id)
        <input type="submit" value="Excluir" class="btn btn-danger" />
    }
</div>

<div>
    <a class="btn btn-primary mt-3" asp-action="Index">Voltar para Lista</a>
</div>

Views/Car/Edit.cshtml
@model CadastroDeCarros.Models.ColorViewModel

@{
    ViewData["Title"] = "Editar Cor";
}
<h1>Editar Cor</h1>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.Id)

    <div>
        @Html.LabelFor(model => model.Descricao)
        @Html.EditorFor(model => model.Descricao)
    </div>

    <div>
        @Html.LabelFor(model => model.Status)
        @Html.DropDownListFor(model => model.Status, (SelectList)ViewBag.StatusList)
    </div>

    <input class="btn btn-primary" type="submit" value="Salvar" />
}


<div>
    <a class="btn btn-danger" asp-action="Index">Voltar para Lista</a>
</div>

Views/Car/Index.cshtml
@model IEnumerable<ColorViewModel>

@{
    ViewData["Title"] = "Lista de Cores";
}

<a class="nav-link text-dark btn btn-primary" asp-area="" asp-controller="Car" asp-action="Create">Cadastrar Carros</a>


<div class="container">
    <h1>Cores</h1>

    <form method="post">
        <div class="form-group">
            <input type="text" class="form-control" id="search" name="search" placeholder="Digite para pesquisar...">
        </div>
        <button type="submit" class="btn btn-primary">Pesquisar</button>
    </form>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Descrição</th>
                <th scope="col">Status</th>
                <th scope="col"></th>

            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Descricao</td>
                    <td>@item.Status</td>
                    <td>
                        <div class="btn-group" role="group">
                            <a class="nav-link text-dark btn btn-success" asp-route-id="@item.Id" asp-area="" asp-controller="Color" asp-action="Edit">Editar</a>
                            <a class="nav-link text-dark btn btn-danger" asp-route-id="@item.Id" asp-area="" asp-controller="Color" asp-action="Delete">Excluir</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>