Models/FuelViewModel.cs
using System.Data.SqlClient;

namespace CadastroDeCarros.Models
{
    public class FuelViewModel
    {
        public int Id { get; set; }
        public required string Descricao { get; set; }
        public required string Status { get; set; }

        public bool CheckIfExists(string descricao)
        {
            bool exists = false;
            string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";

            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                string sqlQuery = "SELECT COUNT(*) FROM Fuel WHERE Description = @Description";
                using (SqlCommand command = new SqlCommand(sqlQuery, connection))
                {
                    command.Parameters.AddWithValue("@Description", descricao);
                    connection.Open();
                    int count = (int)command.ExecuteScalar();
                    if (count > 0)
                    {
                        exists = true;
                    }
                }
            }

            return exists;
        }
    }
}

Controllers/FuelController.cs
using CadastroDeCarros.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Data.SqlClient;

namespace CadastroDeCarros.Controllers
{
    public class FuelController : Controller
    {
        public ActionResult Index()
        {
            List<FuelViewModel> fuels = new List<FuelViewModel>();
            string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))

            {
                connection.Open();

                string sql = "SELECT * FROM Fuel";
                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            FuelViewModel fuel = new FuelViewModel()
                            {
                                Descricao = reader["Description"].ToString(),
                                Status = reader["Status"].ToString(),
                            };

                            fuels.Add(fuel);
                        }
                    }
                }
            }

            return View(fuels);
        }

        [HttpPost]
        public ActionResult Index(string search)
        {
            List<FuelViewModel> fuels = new List<FuelViewModel>();

            string connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
            using (SqlConnection connection = new SqlConnection(connectionString))
            {
                connection.Open();

                string sql;

                if (string.IsNullOrEmpty(search))
                {
                    sql = "SELECT * FROM Fuel";
                }
                else if (search.ToLower() == "ativo" || search.ToLower() == "inativo")
                {
                    sql = "SELECT * FROM Fuel WHERE Status = @Search";
                }
                else
                {
                    sql = "SELECT * FROM Fuel WHERE Description LIKE @Search";
                    search = "%" + search + "%";
                }

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    if (!string.IsNullOrEmpty(search))
                    {
                        command.Parameters.AddWithValue("@Search", search);
                    }
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            FuelViewModel fuel = new()
                            {
                                Descricao = reader["Description"].ToString(),
                                Status = reader["Status"].ToString(),
                            };

                            fuels.Add(fuel);
                        }
                    }
                }
            }

            return View(fuels);
        }



        public ActionResult Create()
        {
            ViewBag.StatusList = new SelectList(new List<string>() { "Ativo", "Inativo" });
            return View();
        }

        [HttpPost]
        public ActionResult Create(FuelViewModel model)
        {
            if (model.CheckIfExists(model.Descricao))
            {
                ModelState.AddModelError("Descricao", "A descrição já foi usada");
                ViewBag.StatusList = new SelectList(new List<string>() { "Ativo", "Inativo" });
                return View(model);
            }

            if (ModelState.IsValid)
            {
                string connectionString ;
                SqlConnection conn;
                connectionString = @"Data Source=PCFABIO\MSSQLSERVER01;Initial Catalog=ShopCar;Integrated Security=True";
                conn = new SqlConnection(connectionString);
                {
                    string sql = "INSERT INTO Fuel (Description, Status) VALUES (@Description, @Status)";
                    using (SqlCommand cmd = new SqlCommand(sql, conn))
                    {
                        cmd.Parameters.AddWithValue("@Description", model.Descricao);
                        cmd.Parameters.AddWithValue("@Status", model.Status);

                        conn.Open();
                        cmd.ExecuteNonQuery();
                    }
                }

                return RedirectToAction("Index");
            }

            return View(model);
        }
    }
}

Views/Fuel/Create.cshtml
@model CadastroDeCarros.Models.FuelViewModel

@{
    ViewData["Title"] = "Cadastro de Combustivel";
}

<h1>Cadastro de Combustivel</h1>

<hr />
@using (Html.BeginForm("Create", "Fuel", FormMethod.Post))
{
    <label for="Descricao">Descrição:</label>
    <input type="text" id="Descricao" name="Descricao" />

    <label for="Status">Status:</label>
    @Html.DropDownListFor(model => model.Status, (SelectList)ViewBag.StatusList)

    <input class = "btn btn-primary" type="submit" value="Enviar" />
}

<br />
<div>
    <a class="btn btn-danger" asp-action="Index">Voltar para lista</a>
</div>

Views/Fuel/Delete.cshtml
@model CadastroDeCarros.Models.FuelViewModel

@{
    ViewData["Title"] = "Deletar Combustível";
}
<h1>Deletar Combustível</h1>

<h2>Tem certeza de que deseja excluir este item?</h2>

<div>
    <h4>Combustível</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>@Html.DisplayNameFor(model => model.Descricao)</dt>
        <dd>@Html.DisplayFor(model => model.Descricao)</dd>

        <dt>@Html.DisplayNameFor(model => model.Status)</dt>
        <dd>@Html.DisplayFor(model => model.Status)</dd>
    </dl>

    @using (Html.BeginForm("DeleteConfirmed", "Fuel"))
    {
        @Html.HiddenFor(model => model.Id)
        <input type="submit" value="Excluir" class="btn btn-danger" />
    }
</div>

<div>
    <a class="btn btn-primary mt-3" asp-action="Index">Voltar para Lista</a>
</div>

Views/Fuel/Edit.cshtml
@model CadastroDeCarros.Models.FuelViewModel

@{
    ViewData["Title"] = "Editar Combustível";
}
<h1>Editar Combustível</h1>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.Id)

    <div>
        @Html.LabelFor(model => model.Descricao)
        @Html.EditorFor(model => model.Descricao)
    </div>

    <div>
        @Html.LabelFor(model => model.Status)
        @Html.DropDownListFor(model => model.Status, (SelectList)ViewBag.StatusList)
    </div>

    <input class="btn btn-primary" type="submit" value="Salvar" />
}


<div>
    <a class="btn btn-danger" asp-action="Index">Voltar para Lista</a>
</div>

Views/Fuel/Index.cshtml
@model IEnumerable<FuelViewModel>

@{
    ViewData["Title"] = "Lista de Combustível";
}

<a class="nav-link text-dark btn btn-primary" asp-area="" asp-controller="Fuel" asp-action="Create">Cadastrar combustiveis</a>


<div class="container">
    <h1>Combustiveis</h1>

    <form method="post">
        <div class="form-group">
            <input type="text" class="form-control" id="search" name="search" placeholder="Digite para pesquisar...">
        </div>
        <button type="submit" class="btn btn-primary">Pesquisar</button>
    </form>

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">Descrição</th>
                <th scope="col">Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Descricao</td>
                    <td>@item.Status</td>
                </tr>
            }
        </tbody>
    </table>
</div>